app = 'trank-api'
primary_region = "iad"

[build]

[http_service]
  internal_port = 3005
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[services.concurrency]
  type = "requests"
  hard_limit = 256
  soft_limit = 128

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024